markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: PhoenixConsoles
author: "Fenix Repair and Development Group"
email: wiki@phoenixconsoles.org
name: "Fenix Repair and Development Group"
url: https://wiki.phoenixconsoles.org/
domain: wiki.phoenixconsoles.org
all_categories: [
["consoles", "Consoles","/posts/android.html"], 
["pc", "PC","/posts/program.html"],
["general", "General","/posts/web.html"], 
["linux", "Linux","/posts/linux.html"],
["rtd", "Research & Development","/posts/read.html"], 
["shop", "Shop","https://www.phoenixconsoles.org/"],
["about", "About Us","https://www.phoenixconsoles.org/"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/New_York

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
